### ISSUE TITLE
[suc-ubuntu-bionic] PIP3 module prometheus_client can not be found

### ISSUE THREAD

**Issue by megian** [projectsyn/system-upgrade-controller-package-upgrade#10]
In the current image docker.io/projectsyn/suc-ubuntu-bionic:20200914 does have an issue with the prometheus_client python module. The issue does not occur in the suc-ubuntu-focal variant.

```
Traceback (most recent call last):
  File "./update_exporter_deb.py", line 4, in <module>
    from prometheus_client import CollectorRegistry, Gauge, pushadd_to_gateway, instance_ip_grouping_key
ModuleNotFoundError: No module named 'prometheus_client'
```

**Comment by corvus-ch** [comment]
There is no indication this is still relevant. So I am going to close this.
