### ISSUE TITLE
Broken image reference in rendered documentation

### ISSUE THREAD

**Issue by arska** [projectsyn/system-upgrade-controller-package-upgrade#30]
https://hub.syn.tools/appcat/explanations/crossplane-secrets-non-provider.html references an image at https://hub.syn.tools/appcat/_images/crossplane-secrets.png which does not exist. The original https://github.com/vshn/component-appcat/blob/master/docs/modules/ROOT/pages/explanations/crossplane-secrets-non-provider.adoc references the image at https://github.com/vshn/component-appcat/raw/master/docs/modules/ROOT/pages/explanations/crossplane-secrets.png where it does exist.

**Comment by simu** [comment]
I'm pretty sure this issue has been opened in the wrong repository.

**Comment by arska** [comment]
Yes, sorry, closing this, replacing with https://github.com/projectsyn/component-hub/issues/68
